### ISSUE TITLE
Support multiple media player

### ISSUE THREAD

**Issue by mnayef95** [ericmatte/ad-media-lights-sync#17]
I think it's will be awesome if the app will support multiple media players, Something like tv and Spotify, and extract colors from them all and reflect them to the lights.

Is this possible?

**Comment by ericmatte** [comment]
Hi, it currently supports multiple type of media players (see the [compatibility section in the README](https://github.com/ericmatte/ad-media-lights-sync#compatibility)), but I've never tried with Spotify.

That aside, I think that you could duplicate the app for every media player you have (one app per media_player). That way, when one media_player changes its associated thumbnail, it would update the lights.

Here is an example in your appdaemon configuration:

```yaml
media_lights_sync:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.tv
  # ...
  lights:
    - light.left_theatre_light
    - light.right_theatre_light

media_lights_sync2:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.tv2
  # ...
  lights:
    - light.left_theatre_light
    - light.right_theatre_light
```

I try to keep this app as simple as possible; let me know it this would solve your idea.
