### ISSUE TITLE
Restore previous light situation when music is over

### ISSUE THREAD

**Issue by jokerigno** [ericmatte/ad-media-lights-sync#24]
**Is your feature request related to a problem? Please describe.**

I think that it would be great if lights are restored to previous status (on off but also brightness).

For example I use this code to change and restore a light status if I turn on main light in a room:

```
  - alias: Studio - Spegni lampade se lampadario si accende
    initial_state: true
    trigger:
    - platform: state
      entity_id: light.studio
      from: 'off'
      to: 'on'
    condition: []
    action:
    - service: scene.create
      data:
        scene_id: studioprima
        snapshot_entities:
        - light.lampada_scrivania
        - light.jack_lamp
    - service: light.turn_off
      data:
        entity_id: 
          - light.lampada_scrivania
          - light.jack_lamp

  - alias: Studio - Accendi lampade se lampadario si spegne (ed erano già accese)
    trigger:
    - platform: state
      entity_id: light.studio
      from: 'on'
      to: 'off'
    condition: []
    action:
    - service: scene.turn_on
      data:
        entity_id: scene.studioprima
```
Can it be added as default in your app?

**Comment by ericmatte** [comment]
What I could probably do is save the status of all lights before changing the colors, and then reset them when the `media_player` is turned off.

Something like this:
```python
self.listen_state(self.reset_lights, self.args["media_player"], new = "off", duration = self.duration)
```

That would reset all the configured lights to their previous status (including brightness).
But I wouldn't call any Home Assistant scenes, as I think that the automations from Home Assistant are preferred for that type of customization.

It could be activated on the app with a `reset_light_when_off` setting (which defaults to `false`).

What do you think? Would that make sense?

---

I also use an automation myself for turning off the lights when the `media_player` is turned off:

```yaml
alias: 'Theatre lights: Turn off when Chromecast shuts off'
trigger:
  - entity_id: media_player.tv
    platform: state
    to: 'off'
    for: '0:00:04'
action:
  - entity_id: light.home_theatre_lights
    service: light.turn_off
```
