### ISSUE TITLE
Changing of color does not work - how to debug?

### ISSUE THREAD

**Issue by jbrepogmailcom** [ericmatte/ad-media-lights-sync#30]
### Describe the bug

Hello, I did installation and configuration exactly by the instructions. However, playing song does not change color o bulb. I checked that media player works fine and retrieves image if album (native mp3 plyer on kodi on libreelec, correctly identified by Home Assistant), I am able to manually change color of the bulb and I believe I have correct assignment as in code below.

Anything else I can do to debug the functionality?

`/config/appdaemon/apps/apps.yaml`:

```yaml
media_lights_sync:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.libreelec
  lights:
    - light.21800710dc4f22741488_2
  ha_url: http://10.0.0.54:8123
  reset_lights_after: true
  use_saturated_colors: false
  use_current_brightness: false
```

I did not find any related entries in home-assistant.log. Nothing in appdaemon log either. I would suspect that in HASSIO image of album is stored in other place than the python script is looking for.

**Comment by jbrepogmailcom** [comment]
I looked at some other issues and their error log show path
/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py

while I have it at
/config/appdaemon/apps/media-lights-sync/media_lights_sync.py

according to github folder names. Which is correct?

**Comment by jbrepogmailcom** [comment]
Anyway, I tried both, no change...

**Comment by jbrepogmailcom** [comment]
could it be that I do not have py3-pillow and Pillow installed? How can I check? In HASSIO the pip install does not work, even python or python3  give "command not found"

**Comment by ericmatte** [comment]
@jbrepogmailcom your configuration seems good.
Also there is no need to manually install anything with HassIO.. Python is already available on your machine for AppDaemon.

The name of the folder shouldn't make any difference, but that should be automatically selected when installing it with HACS. I would suggest you give another shot at installing it with HACS; because HACS is currently the most straight forward way to install any AppDaemon apps on HassIO.

Also for the logs, if you go in HassIO -> Supervisor -> AppDaemon 4 -> Info, there should be a button <kbd>OPEN WEB UI</kbd>.
This will open the AppDaemon manager, and any logs or errors related to AppDaemon and AppDaemon apps will be in there. Installed apps are also listed under `Apps`.

I would also suggest you to read a little more about the documentation of AppDaemon and HACS:
- https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html
- https://hacs.xyz/docs/basic/automation

**Comment by ericmatte** [comment]
If your app is properly installed, you should see in the AppDaemon logs an entry similar to this:
```
INFO media_lights_sync: Listening for picture changes on 'media_player.libreelec'
```

**Comment by jbrepogmailcom** [comment]
I see, thank you very much. First I did not know that appdaemon must be manually started the first time. Second - I started it but it exited because of error. I do not understand why appdaemon.yaml is not there, because in config tab I see proper configuration. There is apps.yaml in apps directory, but not appdaemon.yaml in appdaemon direcotry:

[cont-init.d] appdaemon.sh: executing... 
[16:32:41] FATAL: 
[16:32:41] FATAL: Seems like the /config/appdaemon folder exists,
[16:32:41] FATAL: however appdaemon.yaml wasn't found.
[16:32:41] FATAL: 
[16:32:41] FATAL: Remove or rename the /config/appdaemon folder
[16:32:41] FATAL: and the add-on will create a new and fresh one
[16:32:41] FATAL: for you.
[16:32:41] FATAL: 
[cont-init.d] appdaemon.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing...

**Comment by jbrepogmailcom** [comment]
Hello, finally got it working. There was completely missing appdaemon.yaml and after I created it, I could not find all mandatory parameters. It turned out there were pretty many of them. The example working yaml is here:

appdaemon:
  latitude: 5....
  longitude: 1....
  elevation: 300
  time_zone: Europe/....
  url: http://10.0.0.54:5050
  plugins:
    HASS:
      type: hass
      ha_url: http://10.0.0.54:8123
      token: eyJ0eX.......

**Comment by ericmatte** [comment]
Great! Glad to know you have it running.
Here is my `appdaemon.yaml` config for comparison:

```yaml
secrets: /config/secrets.yaml
appdaemon:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  time_zone: America/Toronto
  plugins:
    HASS:
      type: hass
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
```

You can use [secrets](https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#secrets) if you want too.

I will close this issue.
