### ISSUE TITLE
Better algorithm to identify prevalent colors

### ISSUE THREAD

**Issue by jbrepogmailcom** [ericmatte/ad-media-lights-sync#34]
### Describe the bug

Hello, all colors are still very mild even when I set saturation to true. for example I would expect that for this song the color would be completely red, but in fact it is very light pink: https://www.discogs.com/Jean-Michel-Jarre-The-Concerts-In-China/release/106089

Here is settings in apps.yaml in folder apps:
```yaml
media_lights_sync:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.libreelec
  lights:
    - light.21800710dc4f22741488_2
  ha_url: http://10.0.0.54:8123
  reset_lights_after: true
  use_saturated_colors: true
  use_current_brightness: true
 ```

![image](https://user-images.githubusercontent.com/17232670/107203970-6b6e5500-69fc-11eb-83b7-3032c9e89ed7.png)

Anything I can try? Thank you, Jan
