### ISSUE TITLE
ValueError: A relative URL was received. ha_url must be specified in the configuration for relative URLs.

### ISSUE THREAD

**Issue by jokerigno** [ericmatte/ad-media-lights-sync#40]
### Describe the bug

Hi, just want to share my log with you to doublecheck if it is a bug or a not compatible light.

### Additional context
LOG:
> 2021-05-02 15:18:27.807377 WARNING media_lights_sync_bagno_secondario: ------------------------------------------------------------
> 2021-05-02 15:18:27.807610 WARNING media_lights_sync_bagno_secondario: Unexpected error in worker for App media_lights_sync_bagno_secondario:
> 2021-05-02 15:18:27.807839 WARNING media_lights_sync_bagno_secondario: Worker Ags: {'id': '4fe5cc0a40444be7a8191145063fd0f0', 'name': 'media_lights_sync_bagno_secondario', 'objectid': 'e2970595be33430faa2373a18f75626f', 'type': 'state', 'function': <bound method MediaLightsSync.change_lights_color of <media_lights_sync.MediaLightsSync object at 0x7f4b8eea9250>>, 'attribute': 'entity_picture_local', 'entity': 'media_player.bagno_secondario', 'new_state': '/api/media_player_proxy/media_player.bagno_secondario?token=cccba97d02948d7802b4d830a5035a93d6a0db176e9bef2581046344b4b13c77&cache=818c79654a7d2206', 'old_state': '/api/media_player_proxy/media_player.bagno_secondario?token=cccba97d02948d7802b4d830a5035a93d6a0db176e9bef2581046344b4b13c77&cache=37ce9900470237a0', 'pin_app': True, 'pin_thread': 3, 'kwargs': {'attribute': 'entity_picture_local', '__thread_id': 'thread-3'}}
> 2021-05-02 15:18:27.807994 WARNING media_lights_sync_bagno_secondario: ------------------------------------------------------------
> 2021-05-02 15:18:27.808253 WARNING media_lights_sync_bagno_secondario: Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 903, in worker
>     funcref(
>   File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 56, in change_lights_color
>     url = self.format_url(new_url, entity, attribute)
>   File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 155, in format_url
>     raise ValueError("A relative URL was received on '{entity}.{attribute}'.\nha_url must be specified in the configuration for relative URLs.".format(
> ValueError: A relative URL was received on 'media_player.bagno_secondario.entity_picture_local'.
> ha_url must be specified in the configuration for relative URLs.

CONFIG:
```
media_lights_sync_bagno_secondario:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.bagno_secondario
  photo_attribute: entity_picture
  reset_lights_after: true
  # ha_url: http://192.168.2.101:8123
  use_current_brightness: False
  use_saturated_colors: true
  condition:
    entity: input_boolean.bagnosecondario_musica_da_automazione
    state: "off"
  lights:
    - light.light.striscia_led_bagno_secondario
```

NB: app is called "media_lights_sync_bagno_secondario" because I have another app for lights in another room with following working config:

```
media_lights_sync_studio:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.studio
  photo_attribute: entity_picture
  reset_lights_after: true
  ha_url: http://192.168.2.101:8123
  use_current_brightness: False
  use_saturated_colors: true
  # condition:
    # entity: input_boolean.sync_tv_lights
    # state: "on"
  lights:
    - light.jack_lamp
    - light.lampada_scrivania

```
Thank you
