### ISSUE TITLE
How does it works?

### ISSUE THREAD

**Issue by MrThiemann** [ericmatte/ad-media-lights-sync#42]
hey, I hope is that I rise up a thread here ok?!?

i have been trying to synchronize my lamps with music for many hours...

I installed appdaemon as an integration in the supervisor. I also installed this add-on and hopefully adjusted it correctly.

but maybe I misunderstood all of this ...
this morning i already wrote some scenes for the party light. that works quite well so far.

now I would like to trigger this a bit with the music;)
what does this addon do?

When music is playing on a media player, do the lights change color?

````
spotify_mood_lights_sync:
  module: spotify_mood_lights_sync
  class: SpotifyMoodLightsSync
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
  media_player: media_player.nathalies_echo_dot
  light: light.extended_color_light_2
  color_profile: default
  mode: direct
  max_retries: 1
  custom_profile:
    - point: [ 0, 0 ]
      color: [ 0, 0, 255 ]
    - point: [ 1, 0 ]
      color: [ 0, 255, 0 ]
    - point: [ 0, 1 ]
      color: [ 255, 0, 0 ]
    - point: [ 1, 1 ]
      color: [ 255, 255, 0 ]
````

**Comment by ericmatte** [comment]
Hi @MrThiemann,

I think you are confusing this app with the [Spotify Mood Lights Sync](https://github.com/NiklasReiche/ad-spotify-mood-lights-sync) app.

---

If this is not the case, this app, ad-media-lights-sync, is used to synchronize your RGB light with the thumbnail (artwork) of the currently playing song. Take a look at the [README](https://github.com/ericmatte/ad-media-lights-sync) for more information about it and how to set it up.

It is not real-time, but changes each time their is a new song.

I will close this issue, as I don't think it is related to this app. Feel free to re-open it if anything.

**Comment by Akszyn** [comment]
how to sync the lighting with a movie step by step in Home Assistant? because I installed the AppDaemon app and downloaded from HACS and added these 2 lines in the add-on settings and created a file in the mentioned directory with the following data
```
media_lights_sync:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.android_tv_192_168_5_130
  lights:
    - light.korytarz
    - light.led_5m
    - light.salon
  ha_url: http://homeassistant.local:8123/
  reset_lights_after: true
  use_saturated_colors: false
  use_current_brightness: false
  condition:
    entity: input_boolean.sync_tv_lights
    state: "on"
```
I don’t know what’s next because there’s no information about it on the page for this addon
