### ISSUE TITLE
Help configuration for Condition

### ISSUE THREAD

**Issue by jokerigno** [ericmatte/ad-media-lights-sync#44]
### Describe the bug

I want to use media-light-sync only at night and if a switch for party mode is off. So I added a condition as following:

```

media_lights_sync_studio:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.studio
  lights:
    - light.jack_lamp
    - light.lampada_scrivania
  ha_url: http://192.168.2.101:8123
  reset_lights_after: true
  use_saturated_colors: true
  use_current_brightness: false
  condition:
    - condition: template
      value_template: >-
        "{{ is_state('switch.lafesta', 'off') and state_attr('sun.sun', 'elevation') | int < 2 }}"
```

Below the logs:

> 2021-09-08 16:03:29.687804 WARNING media_lights_sync_studio: ------------------------------------------------------------
> 2021-09-08 16:03:29.696478 WARNING media_lights_sync_studio: ------------------------------------------------------------
> 2021-09-08 16:03:29.696873 WARNING media_lights_sync_studio: Unexpected error in worker for App media_lights_sync_studio:
> 2021-09-08 16:03:29.697468 WARNING media_lights_sync_studio: Worker Ags: {'id': '9a01d37e74ca413a8b6f53bd81e8d6df', 'name': 'media_lights_sync_studio', 'objectid': '2b62939a27424a349243e6d690693394', 'type': 'state', 'function': <bound method MediaLightsSync.change_lights_color of <media_lights_sync.MediaLightsSync object at 0x7fc00e5babb0>>, 'attribute': 'entity_picture', 'entity': 'media_player.studio', 'new_state': 'https://i.scdn.co/image/ab67616d00001e02232711f7d66a1e19e89e28c5', 'old_state': 'https://i.scdn.co/image/ab67616d00001e02caaa456c44f69f10c8b2aa53', 'pin_app': True, 'pin_thread': 3, 'kwargs': {'attribute': 'entity_picture', '__thread_id': 'thread-3'}}
> 2021-09-08 16:03:29.697766 WARNING media_lights_sync_studio: ------------------------------------------------------------
> 2021-09-08 16:03:29.698164 WARNING media_lights_sync_studio: Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 903, in worker
>     funcref(
>   File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 42, in change_lights_color
>     if new_url == old_url or not self.can_change_colors():
>   File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 71, in can_change_colors
>     return self.condition is None or self.get_state(self.condition["entity"]) == self.condition["state"]
> TypeError: list indices must be integers or slices, not str
> 
> 2021-09-08 16:03:29.698385 WARNING media_lights_sync_studio: ------------------------------------------------------------

Some time ago this config worked for a while:

```
media_lights_sync_studio:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.studio
  lights:
    - light.jack_lamp
    - light.lampada_scrivania
  ha_url: http://192.168.2.101:8123
  reset_lights_after: true
  use_saturated_colors: true
  use_current_brightness: false
  condition:
    - entity:  switch.lafesta
      state: "off"
    - condition: template
      value_template: "{{ state_attr('sun.sun', 'elevation') < 2 }}"
```

### Environment versions

- ad-media-lights-sync: 1.0.0
- Home Assistant: 2021.9.4
- AppDaemon: 0.7.0 (add on version) 

Any hint?

**Comment by ericmatte** [comment]
Hello @jokerigno,

please refer to the [App Configuration](https://github.com/ericmatte/ad-media-lights-sync#app-configuration) section of the README.

The problem is that you are adding multiple conditions to the configuration, but this simple app **only takes one** condition.
That condition allow lights sync only when the state is matched.

Here is an example with an input_boolean (the indentation is important):

```yaml
  # ...
  condition:
    entity: input_boolean.sync_tv_lights
    state: "on"
```

> Some time ago this config worked for a while

I'm pretty sure that was never the case 🤔 

I will close this issue, as it is intended to work with only one condition.
