### ISSUE TITLE
Help with initial setup

### ISSUE THREAD

**Issue by PottsNet** [ericmatte/ad-media-lights-sync#52]
I have set up Media Lights Sync in my Home Assistant and I don’t seem to be getting any errors but I cant work out how to execute the app as the lights are not changing.   What so you think I might be missing?  I have never set up an app using AppDaemon before.  I used HACS to setup.

My AppDaemon config:

```
init_commands: []
python_packages:
  - Pillow
system_packages:
  - py3-pillow
log_level: info
```

Apps yaml:

```
media_lights_sync:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.lounge_apple_tv_2
  lights:
    - light.feibit_inc_co_fb56_zcw11hg1_2_2f49db13_level_light_color_on_off
    - light.feibit_inc_co_fb56_zcw11hg1_2_level_light_color_on_off
    - light.feibit_inc_co_fb56_zcw11hg1_2_8c99ed13_level_light_color_on_off
    - light.feibit_inc_co_fb56_zcw11hg1_2_7f0eca13_level_light_color_on_off
    - light.feibit_inc_co_fb56_zcw11hg1_2_d161ed13_level_light_color_on_off
    - light.feibit_inc_co_fb56_zcw11hg1_2_44f1c913_level_light_color_on_off
    - light.signify_netherlands_b_v_lct010_44b41a04_level_light_color_on_off
    - light.signify_netherlands_b_v_lst002_150cae02_level_light_color_on_off
  ha_url: http://homeassistant.local:8123
  reset_lights_after: true
  use_saturated_colors: true
  use_current_brightness: false
  condition:
    entity: input_boolean.sync_tv_lights
    state: "on"
```

**Comment by PottsNet** [comment]
Under Entities in AppDaemon the callback are increasing by one with every song.

**Comment by PottsNet** [comment]
Not sure if this helps?

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/42736500/160271765-a84631a1-37c9-45b5-8b46-2d7d06b7f269.png">

**Comment by PottsNet** [comment]
appdaemon.yaml
```
secrets: /config/secrets.yaml
appdaemon:
  latitude: xxxxxx
  longitude: xxxxxx
  elevation: 70
  time_zone: Australia/Sydney
  plugins:
    HASS:
      type: hass
http:
  url: http://homeassistant.local:5050
admin:
api:
hadashboard:
```
