### ISSUE TITLE
Multiple sync areas creation

### ISSUE THREAD

**Issue by Cagataykrpnr** [ericmatte/ad-media-lights-sync#69]
I am not sure that is already possible or not but I could not create 2 or more different players to sync lights with different areas. Would be amazing to create sync options for multiple media players

**Comment by ericmatte** [comment]
Hi, yes you can!

There is two ways to do this.

### 1. Syncing multiple `media_player` to the same groups of lights

Just add all your media players as a list in the config:

```yml
media_lights_sync:
  module: media_lights_sync
  class: MediaLightsSync
  media_player:
    - media_player.living_room_tv
    - media_player.bedroom_tv
  lights:
    - light.first_light
    - light.second_light
  ha_url: !secret ha_url
```

### 2. Syncing multiple `media_player` to the **different** groups of lights:

You can create multiple AppDaemon app instances like so.
Each app will be independent.

```yml
media_lights_sync_1:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.living_room_tv
  lights:
    - light.first_light
    - light.second_light
  ha_url: !secret ha_url

media_lights_sync_2:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.bedroom_tv
  lights:
    - light.third_light
  ha_url: !secret ha_url
```

Feel free to reopen this issue if needed.
