### ISSUE TITLE
Using chromecast Native app rather than google cast :  entity_picture_local

### ISSUE THREAD

**Issue by jawshr26** [ericmatte/ad-media-lights-sync#71]
Hello,hope you can point me in the right direction.  Casting from a device traditionally will give me a value on the entities Entity Picture parameter, but not with any native apps on the Chromecast with Google TV.
Feels like I'm close but do I need a separate intergration for the google TV apps?

Thanks heaps 

PS. HomeAssistantOS latest version on rpi4. Here's my `apps.yaml`:
```yml
media_lights_sync:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.bedroom_tv
  lights:
    - light.corner_lamp
    - light.dining_lamp
  ha_url: http://homeassistant.local:8123/
  reset_lights_after: true
  use_saturated_colors: false
  use_current_brightness: false
  condition:
    entity: input_boolean.sync_tv_lights
    state: "on"
```
