### ISSUE TITLE
ValueError("A relative URL was received on '{entity}.{attribute}'.

### ISSUE THREAD

**Issue by Dean98T** [ericmatte/ad-media-lights-sync#72]
In the logs for the AppDaemon app whenever I run this, as soon as the Spotify entity picture changes, with it being a relative URL, I get the following error message:

```
  File `/config/apps/media_lights_sync.py`, line 174, in format_url
    raise ValueError("A relative URL was received on '{entity}.{attribute}'.\nha_url must be specified in the configuration for relative URLs.".format(
ValueError: A relative URL was received on 'media_player.spotify_dean_taylor.entity_picture'.
ha_url must be specified in the configuration for relative URLs.
```

CONFIG:

APP
```yml
media_lights_sync:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.spotify_dean_taylor
  lights:
    - light.left_lamp
    - light.right_lamp
    - light.office_light
  ha_url: http://homeassistant.local:8123/
  reset_lights_after: true
  use_saturated_colors: false
  use_current_brightness: false
```

APPDAEMON
```yml
appdaemon:
  latitude: *
  longitude: *
  elevation: 30
  time_zone: Europe/London
  plugins:
    HASS:
      type: hass
      ha_url: http://homeassistant.local:8123/
      token: *
```
