### ISSUE TITLE
custom effects, brightness control

### ISSUE THREAD

**Issue by prankousky** [ericmatte/ad-media-lights-sync#8]
Hi,

I just got this running thanks to the help in the (now solved) issue https://github.com/ericmatte/ad-media-lights-sync/issues/7; so I thought I'd pitch an idea to implement a feature allowing users to chose an -**or ideally, multiple**- effect(s) to use.

My test light is a `WLED`; it will run the `Meteor` effect when started manually (usually my lights are started via `scene` to automatically be set to correct brightness, color, and perhaps effect). 

I thought the following might be nice additional features:

* define which effect (or effect**s**) to apply when using this script
* allow to cycle through those effects via configurable period of time
* define brightness to apply when initially starting this script

Something like

```
media_lights_sync:
# (...)
  use_current_brightness: False
  effect: "Breathe" # OR if multiple effects
  effects:
    - "Breathe" 
    - "Smooth Meteor"
    - "Twinklefox"
  cycle_effects: True # and IF TRUE
  cycle_period: 5    # apply different effect every 5 minutes
  brightness: 120
# (...)
```

Also something that just came to mind while typing this: define an effect and/or color in case cover art is either plain white (or brighter than threshold <x>), and/or if there is no cover art available.

Unfortunately, I am having a very hard time with writing appdaemon scripts (simply not enough knowledge about programming), so I cannot implement this, at least not any time soon. 

Cheers!
